chore: delete old workflows

diff --git a/.github/actions/artifacts/action.yml b/.github/actions/artifacts/action.yml
--- a/.github/actions/artifacts/action.yml
+++ b/.github/actions/artifacts/action.yml
@@ -28,17 +28,17 @@ runs:
         git commit --allow-empty -m "[AUTO] build ${{ inputs.name }} from ${GITHUB_SHA}"
 
         ATTEMPT=0
-        MAX_ATTEMPTS=5
+        MAX_ATTEMPTS=10
         function push_changes() {
           ATTEMPT=$((ATTEMPT+1))
-          if [[ $ATTEMPT -eq $MAX_ATTEMPTS ]]; then
-            echo "[ERROR] Pushing failed" >&2
-            exit 1
-          fi
           echo "[INFO] Pulling latest changes from remote..."
           git pull --rebase origin "${GITHUB_REF_NAME}"
           echo "[INFO] Pushing changes..."
           if ! git push; then
+            if [[ $ATTEMPT -eq $MAX_ATTEMPTS ]]; then
+              echo "[ERROR] Pushing failed" >&2
+              exit 1
+            fi
             echo "[WARN] Push conflict detected. Retrying in 10 seconds..."
             sleep 10
             push_changes || exit 1
